# Stage 1: Build the application
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Run the application
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Set environment variables
ARG DATASOURCE_ALTOUR_DB_DEV
ARG USERNAME_POSTGRES
ARG PASSWORD_POSTGRES
ARG JWT_SECRET_KEY
ARG API_KEY_HERE_MAPS_ALTOUR
ARG API_PRIV_KEY_BEST_TIME_ALTOUR
ARG API_PUB_KEY_HERE_MAPS_ALTOUR
ARG REDIS_PASSWORD
ARG AES_KEY

ENV DATASOURCE_ALTOUR_DB_DEV=$DATASOURCE_ALTOUR_DB_DEV
ENV USERNAME_POSTGRES=$USERNAME_POSTGRES
ENV PASSWORD_POSTGRES=$PASSWORD_POSTGRES
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV API_KEY_HERE_MAPS_ALTOUR=$API_KEY_HERE_MAPS_ALTOUR
ENV API_PRIV_KEY_BEST_TIME_ALTOUR=$API_PRIV_KEY_BEST_TIME_ALTOUR
ENV API_PUB_KEY_HERE_MAPS_ALTOUR=$API_PUB_KEY_HERE_MAPS_ALTOUR
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV AES_KEY=$AES_KEY

# Expose port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java","-jar","app.jar"]